### PR TITLE
Add head or body script tag to page template

### PR DESCRIPTION
**Pull request by maxlibin**
<strike>This allow darkMode option for each page by adding a prop allowDarkMore in pageBuilder record.</strike>

This PR add an option to pass in script tag in either Head or Body part as array
`scripts: array<script>`

in your page option, you will use something like this:

```
    ...   
    headCssFilepaths: headCssFilepaths,
    path: path,
    globalValues: Some(globalValues),
    scripts: [{RescriptSsg.PageBuilder.location: Body, text: darkModeScript}],
```

open for discussion.

### CODE REVIEW

**Comment by denis-ok** [comment]
@maxlibin 
Thanks for the PR!

I feel that this code and change is a bit too specific to some requirements of a certain codebase and probably not really reusable. It forces to use constants that are used in the script and they that aren't exposed anywhere. I mean `"mode"` and `"dark"`.

I would really prefer if instead of this change, we add support and just allow inserting arbitrary script tags to head or to body.

**Comment by maxlibin** [comment]
Changed to use script tag instead of adding dark mode directly @denis-ok

**Comment by denis-ok** [comment]
@maxlibin Looks great, thanks!

**Comment by denis-ok** [comment]
@maxlibin I did a bit of refactoring and decided to just add `headScripts` and `bodyScripts` fields to page.
It seems simper to me, no need to filter array.
Please take a look:
https://github.com/denis-ok/rescript-ssg/commit/c4e49873698a8e459bcef8c0beee74488da8c8f4

**Comment by maxlibin** [comment]
cool, looks good too, thanks.

**Pull request merged**
